# æœºå™¨äººWxId
botWxId: "wxid_lbzw1d5b3pwl29"
# æœºå™¨äººåå­—
botNickname: "YY BotğŸ¤–"
# ç®¡ç†å‘˜WxId
superUsers:
  - "wxid_5cvtxuwufytd21"
# ç®¡ç†å‘˜å‘½ä»¤å‰ç¼€
commandPrefix: "/"
# æ¡†æ¶é…ç½®
frameworks:
  # æ¡†æ¶é€‰æ‹©ï¼Œå¯é€‰ qianxunã€vlw
  name: "qianxun"
  # http api åœ°å€(ip+ç«¯å£ç»„æˆ)
  apiUrl: "http://192.168.31.8:9527"
  # http api token
  apiToken: "7k7k"
  # æœºå™¨äººå›è°ƒæœåŠ¡ç«¯å£
  servePort: 9528